# Generated by Django 5.2 on 2025-08-13 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_advisorschedule_scheduleexception_weekoff"),
        ("store", "0006_storegeofence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_in_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="attendance/checkins/"
                    ),
                ),
                (
                    "check_out_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="attendance/checkouts/"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="Attendance date is the shift START calendar day.",
                    ),
                ),
                ("check_in", models.DateTimeField(blank=True, null=True)),
                (
                    "check_in_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "check_in_lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "check_out_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "check_out_lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("early_out_minutes", models.PositiveIntegerField(default=0)),
                (
                    "ot_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Counted only when OT is approved in later phases.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PRESENT", "Present"),
                            ("HALF_DAY", "Half Day"),
                            ("ABSENT", "Absent"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendances",
                        to="attendance.shift",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendances",
                        to="store.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "advisor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "date"], name="attendance__store_i_5ddcda_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date", "shift"), name="unique_user_date_shift"
                    )
                ],
            },
        ),
    ]
