# Generated by Django 5.2 on 2025-08-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
