# Generated by Django 5.2 on 2025-08-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_store_latitude_store_longitude_store_radius"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="store",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="store",
            name="radius",
        ),
    ]
