# Generated by Django 5.2 on 2025-08-24 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    Store = apps.get_model("store", "Store")
    for store in Store.objects.all():
        if getattr(store, "branch_head_id", None):
            store.authority_id = store.branch_head_id
            store.save(update_fields=["authority"])


def backwards(apps, schema_editor):
    Store = apps.get_model("store", "Store")
    for store in Store.objects.all():
        if getattr(store, "authority_id", None):
            store.branch_head_id = store.authority_id
            store.save(update_fields=["branch_head"])


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_storegeofence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="authority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_stores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="store_type",
            field=models.CharField(
                choices=[("HQ", "Head Office"), ("BRANCH", "Branch")],
                default="BRANCH",
                max_length=6,
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="store",
            name="branch_head",
        ),
    ]
