# Generated by Django 5.2 on 2025-08-24 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_quality_unit_product_unit"),
        ("spares", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spare",
            name="quality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spares",
                to="catalog.quality",
            ),
        ),
    ]
