# Generated by Django 5.2 on 2025-08-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_admin_role_to_system_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("system_admin", "System Admin"),
                    ("branch_head", "Branch Head"),
                    ("advisor", "Advisor"),
                    ("customer", "Customer"),
                ],
                default="advisor",
                max_length=12,
            ),
        ),
    ]
