# Generated by Django 5.2.5 on 2025-10-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_quality_unit_product_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
