# Generated by Django 5.2 on 2025-08-12 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("alternate_weekly", "Alternate Weekly"),
                        ],
                        default="fixed",
                        max_length=32,
                    ),
                ),
                (
                    "anchor_monday",
                    models.DateField(
                        help_text="A Monday used to compute week parity (even/odd)."
                    ),
                ),
                (
                    "parity_offset",
                    models.SmallIntegerField(
                        choices=[(0, "Even as A"), (1, "Odd as A")],
                        default=0,
                        help_text="Flip weekly parity to support batches (0=no flip, 1=flip).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_shift",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for fixed rule.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_for_schedules",
                        to="attendance.shift",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "advisor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "week_even_shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="week_even_for_schedules",
                        to="attendance.shift",
                    ),
                ),
                (
                    "week_odd_shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="week_odd_for_schedules",
                        to="attendance.shift",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "mark_off",
                    models.BooleanField(
                        default=False,
                        help_text="If true, treat as off-day regardless of shift.",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "override_shift",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, use this shift for the date.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attendance.shift",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "advisor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_schedule_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"),
                        name="unique_scheduleexception_user_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeekOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.SmallIntegerField(help_text="0=Mon … 6=Sun")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "advisor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_weekoffs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "weekday"), name="unique_weekoff_user_weekday"
                    )
                ],
            },
        ),
    ]
