# Generated by Django 5.2.5 on 2025-10-16 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_no",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("retail_sale", "Retail Sale"),
                            ("repair_service", "Repair Service"),
                        ],
                        default="retail_sale",
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_phone", models.CharField(max_length=15)),
                ("customer_address", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cgst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "sgst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "igst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleInvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("hsn_code", models.CharField(blank=True, max_length=8)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="sales.saleinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="saleinvoice",
            index=models.Index(
                fields=["invoice_no"], name="sales_salei_invoice_46f088_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleinvoice",
            index=models.Index(
                fields=["-created_at"], name="sales_salei_created_c3053a_idx"
            ),
        ),
    ]
