# Generated by Django 5.2 on 2025-08-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_issue_otherissue_question_booking_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
