from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('schedulecall/', views.scheduleCall, name='schedulecall'),
    path('locate/', views.locate, name='locate'),
    path('contact/', views.contact, name='contact'),
    path('terms-and-conditions/', views.terms, name='terms'),
    path('validateavailability/', views.getLocationAvailability, name='validateAvailability'),
    path('submitbooking/', views.submitBooking, name='submitbooking'),
    path('sendotp/', views.sendOTP, name='sendotp'),
    path('newspare/', views.newSpare, name="newspare"),
    path('checkproductexistance/', views.checkProductExistance, name="checkproductexistance"),
    path('bookings/', views.BookingsView, name="bookings"),
    path('loginpage/', views.loginPage, name='loginpage'),
    path('login/', views.userLogin, name='login'),
    path('logout/', views.userLogout, name='logout'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('price-check/', views.priceCheck, name="pricecheck"),
    path('price-maintanence/', views.priceMaintanence, name="pricemaintanence"),
    path('repairuser/', views.getRepairUser, name="repairuser"),
    path('request/', views.request, name="request"),
    path('saveprice/', views.savePrice, name="saveprice"),
    path('saveprice-updated/', views.savePriceUpdate, name="saveprice"),
    path('noaccess/', views.noAccessPage, name="noaccesspage"),
    path('adduser/', views.addUser, name="adduser"),
    path('product-manager/', views.productManagement, name="productmanager"),
    path('closerequest/<int:id>', views.closeRequest, name="closerequest"),
    path('allbookings/', views.allBookings, name='allbookings'),
    path('stores/', views.stores, name='stores'),
    path('reports/', views.reports, name='reports'),
    path('orders/', views.orders, name='orders'),
    path('tasks/', views.tasks, name='tasks'),
    path('questions/', views.questions, name='questions'),
    # path('accounts/', include('django.contrib.auth.urls')),
]
