# Generated by Django 5.2 on 2025-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.URLField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now=True)),
                ("date_modified", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("mobile_no", models.CharField(max_length=10)),
                ("message", models.TextField(max_length=1555)),
                ("date_added", models.DateTimeField(auto_now=True)),
                ("date_modified", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.CharField(max_length=255)),
                ("time", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, max_length=855, null=True)),
            ],
        ),
    ]
