name: Sync Frontend and Backend Repos

on:
  schedule:
    - cron: '0 */6 * * *'   # 00:00, 06:00, 12:00, 18:00 UTC (05:30/11:30/17:30/23:30 IST)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: sync-repos
  cancel-in-progress: true

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      # Checkout the analysis repo with RW token (pushes back here)
      - name: Checkout analysis repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WRITE_TOKEN }}   # Fine-grained PAT: Contents Read & Write for THIS repo
          fetch-depth: 1

      - name: Configure git
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "sync-bot"
          git config user.email "sync-bot@krishamaze.com"

      - name: Clean work dirs
        run: rm -rf frontend backend temp-frontend temp-backend

      # -------- Preflight: verify FE/BE branches exist (fast fail) --------
      - name: Preflight: verify FE/BE branches
        shell: bash
        env:
          READ_PAT: ${{ secrets.READ_TOKEN }}   # Fine-grained PAT: Contents Read for FE+BE repos
        run: |
          set -euo pipefail
          CLEAN="$(printf '%s' "$READ_PAT" | tr -d '\r\n')"
          BASIC="$(printf 'x-access-token:%s' "$CLEAN" | base64 -w0 2>/dev/null || printf 'x-access-token:%s' "$CLEAN" | base64 | tr -d '\n')"

          chk() {
            local REPO="$1" BR="$2"
            git -c http.extraHeader="Authorization: Basic ${BASIC}" \
              ls-remote --heads "https://github.com/krishamaze/${REPO}.git" "$BR" >/dev/null
            echo "OK: ${REPO}#${BR}"
          }

          chk finetune-ERP-frontend feature/dashboard-integration
          chk finetune-ERP-backend  krishna/implement-phase-a1-admin-api-scaffold

      # -------- Clone with Basic header (Git over HTTPS uses Basic, not Bearer) --------
      - name: Clone Frontend
        shell: bash
        env:
          READ_PAT: ${{ secrets.READ_TOKEN }}
        run: |
          echo "Cloning Frontend..."
          git clone --depth 1 --branch feature/dashboard-integration \
              https://x-access-token:${{ secrets.READ_TOKEN }}@github.com/krishamaze/finetune-ERP-frontend.git temp-frontend
          echo "Frontend clone successful"
          test -d temp-frontend/.git || { echo "Frontend checkout failed"; exit 1; }

      # Clone backend using token authentication
      - name: Clone Backend
        run: |
          echo "Cloning Backend..."
          git clone --depth 1 --branch krishna/implement-phase-a1-admin-api-scaffold \
              https://x-access-token:${{ secrets.READ_TOKEN }}@github.com/krishamaze/finetune-ERP-backend.git temp-backend
          echo "Backend clone successful"
          test -d temp-backend/.git || { echo "Backend checkout failed"; exit 1; }

      - name: Copy files (excluding git history)
        run: |
          mkdir -p frontend backend
          cp -r temp-frontend/* frontend/ 2>/dev/null || true
          cp -r temp-frontend/.[!.]* frontend/ 2>/dev/null || true
          cp -r temp-backend/*  backend/  2>/dev/null || true
          cp -r temp-backend/.[!.]* backend/ 2>/dev/null || true
          rm -rf temp-frontend temp-backend frontend/.git backend/.git

      - name: Remove sensitive files
        run: |
          find frontend backend -name ".env*" -delete 2>/dev/null || true
          find frontend backend -name "node_modules" -type d -exec rm -rf {} + 2>/dev/null || true
          find frontend backend -name ".git" -type d -exec rm -rf {} + 2>/dev/null || true

      - name: Create sync info
        run: |
          cat << 'EOF' > SYNC_INFO.md
          # Repo Sync Information

          **Last Synced:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')

          **Frontend Branch:** feature/dashboard-integration
          **Backend Branch:** krishna/implement-phase-a1-admin-api-scaffold

          **Frontend Repo:** https://github.com/krishamaze/finetune-ERP-frontend.git
          **Backend Repo:** https://github.com/krishamaze/finetune-ERP-backend.git
          EOF

      - name: Commit and push changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync repos: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
            echo "Changes synced successfully!"
          fi
