name: Sync Frontend and Backend Repos

on:
  schedule:
    - cron: '0 */6 * * *'  # Fixed: removed extra asterisk
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: sync-repos
  cancel-in-progress: true

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout analysis repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WRITE_TOKEN }}
          fetch-depth: 1

      - name: Configure git
        run: |
          git config user.name "sync-bot"
          git config user.email "sync-bot@krishamaze.com"

      - name: Clean work dirs
        run: rm -rf frontend backend temp-frontend temp-backend

      # Clone frontend using Bearer token header
      - name: Clone Frontend
        run: |
          echo "Cloning Frontend..."
          git -c http.extraHeader="Authorization: Bearer ${{ secrets.READ_TOKEN }}" \
              clone --depth 1 --branch feature/dashboard-integration \
              https://github.com/krishamaze/finetune-ERP-frontend.git temp-frontend
          echo "Frontend clone successful"
          test -d temp-frontend/.git || { echo "Frontend checkout failed"; exit 1; }

      # Clone backend using Bearer token header
      - name: Clone Backend
        run: |
          echo "Cloning Backend..."
          git -c http.extraHeader="Authorization: Bearer ${{ secrets.READ_TOKEN }}" \
              clone --depth 1 --branch krishna/implement-phase-a1-admin-api-scaffold \
              https://github.com/krishamaze/finetune-ERP-backend.git temp-backend
          echo "Backend clone successful"
          test -d temp-backend/.git || { echo "Backend checkout failed"; exit 1; }

      - name: Copy files (excluding git history)
        run: |
          mkdir -p frontend backend
          cp -r temp-frontend/* frontend/ 2>/dev/null || true
          cp -r temp-frontend/.[!.]* frontend/ 2>/dev/null || true
          cp -r temp-backend/*  backend/  2>/dev/null || true
          cp -r temp-backend/.[!.]* backend/ 2>/dev/null || true
          rm -rf temp-frontend temp-backend frontend/.git backend/.git

      - name: Remove sensitive files
        run: |
          find frontend backend -name ".env*" -delete 2>/dev/null || true
          find frontend backend -name "node_modules" -type d -exec rm -rf {} + 2>/dev/null || true
          find frontend backend -name ".git" -type d -exec rm -rf {} + 2>/dev/null || true

      - name: Create sync info
        run: |
          cat << 'EOF' > SYNC_INFO.md
          # Repo Sync Information

          **Last Synced:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')

          **Frontend Branch:** feature/dashboard-integration
          **Backend Branch:** krishna/implement-phase-a1-admin-api-scaffold

          **Frontend Repo:** https://github.com/krishamaze/finetune-ERP-frontend.git
          **Backend Repo:** https://github.com/krishamaze/finetune-ERP-backend.git
          EOF

      - name: Commit and push changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync repos: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
            echo "Changes synced successfully!"
          fi
