name: Sync Frontend and Backend Repos

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: sync-repos
  cancel-in-progress: true

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout analysis repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WRITE_TOKEN || github.token }}
          fetch-depth: 1

      - name: Configure git
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "sync-bot"
          git config user.email "sync-bot@krishamaze.com"

      - name: Remove existing folders
        run: rm -rf frontend backend temp-frontend temp-backend

      - name: Clone Frontend
        env:
          READ_PAT: ${{ secrets.READ_TOKEN }}
          FE_URL: ${{ vars.FE_REPO_URL }}   # e.g., https://github.com/krishamaze/finetune-ERP-frontend.git
        shell: bash
        run: |
          set -euo pipefail
          echo "Cloning Frontend…"
          # Extract the repo path without https://
          REPO_PATH="${FE_URL#https://github.com/}"
          git clone --depth 1 --branch feature/dashboard-integration \
            "https://x-access-token:${READ_PAT}@github.com/${REPO_PATH}" temp-frontend
          test -d temp-frontend/.git || { echo "Frontend checkout failed"; exit 1; }

      - name: Clone Backend
        env:
          READ_PAT: ${{ secrets.READ_TOKEN }}
          BE_URL: ${{ vars.BE_REPO_URL }}   # e.g., https://github.com/krishamaze/finetune-ERP-backend.git
        shell: bash
        run: |
          set -euo pipefail
          echo "Cloning Backend…"
          # Extract the repo path without https://
          REPO_PATH="${BE_URL#https://github.com/}"
          git clone --depth 1 --branch krishna/implement-phase-a1-admin-api-scaffold \
            "https://x-access-token:${READ_PAT}@github.com/${REPO_PATH}" temp-backend
          test -d temp-backend/.git || { echo "Backend checkout failed"; exit 1; }

      - name: Copy files (excluding git history)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p frontend backend
          cp -r temp-frontend/* frontend/ 2>/dev/null || true
          cp -r temp-frontend/.[!.]* frontend/ 2>/dev/null || true
          cp -r temp-backend/*  backend/  2>/dev/null || true
          cp -r temp-backend/.[!.]* backend/ 2>/dev/null || true
          rm -rf temp-frontend temp-backend frontend/.git backend/.git

      - name: Remove sensitive files
        run: |
          find frontend backend -name ".env*" -delete 2>/dev/null || true
          find frontend backend -name "node_modules" -type d -exec rm -rf {} + 2>/dev/null || true
          find frontend backend -name ".git" -type d -exec rm -rf {} + 2>/dev/null || true

      - name: Create sync info
        shell: bash
        run: |
          set -euo pipefail
          {
            echo "# Repo Sync Information"
            echo
            echo "**Last Synced:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            echo
            echo "**Frontend Branch:** feature/dashboard-integration"
            echo "**Backend Branch:** krishna/implement-phase-a1-admin-api-scaffold"
            echo
            echo "**Frontend Repo:** ${{ vars.FE_REPO_URL }}"
            echo "**Backend Repo:** ${{ vars.BE_REPO_URL }}"
          } > SYNC_INFO.md

      - name: Commit and push changes
        shell: bash
        run: |
          set -euo pipefail
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync repos: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
            echo "Changes synced successfully!"
          fi
