name: Sync Frontend and Backend Repos

on:
  schedule:
    - cron: '0 */6 * * *'   # 00:00, 06:00, 12:00, 18:00 UTC (05:30/11:30/17:30/23:30 IST)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: sync-repos
  cancel-in-progress: true

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      # Checkout the analysis repo with RW token (pushes back here)
      - name: Checkout analysis repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WRITE_TOKEN }}   # Fine-grained PAT: Contents Read & Write for THIS repo
          fetch-depth: 1

      - name: Configure git
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "sync-bot"
          git config user.email "sync-bot@krishamaze.com"

      - name: Clean work dirs
        run: rm -rf frontend backend temp-frontend temp-backend

      # -------- Preflight: verify FE/BE branches exist (fast fail) --------
      - name: Preflight: verify FE/BE branches
        shell: bash
        env:
          READ_PAT: ${{ secrets.READ_TOKEN }}   # Fine-grained PAT: Contents Read for FE+BE repos
        run: |
          set -euo pipefail
          CLEAN="$(printf '%s' "$READ_PAT" | tr -d '\r\n')"
          BASIC="$(printf 'x-access-token:%s' "$CLEAN" | base64 -w0 2>/dev/null || printf 'x-access-token:%s' "$CLEAN" | base64 | tr -d '\n')"

          chk() {
            local REPO="$1" BR="$2"
            git -c http.extraHeader="Authorization: Basic ${BASIC}" \
              ls-remote --heads "https://github.com/krishamaze/${REPO}.git" "$BR" >/dev/null
            echo "OK: ${REPO}#${BR}"
          }

          chk finetune-ERP-frontend feature/dashboard-integration
          chk finetune-ERP-backend  krishna/implement-phase-a1-admin-api-scaffold

      # -------- Clone with Basic header (Git over HTTPS uses Basic, not Bearer) --------
      - name: Clone Frontend
        shell: bash
        env:
          READ_PAT: ${{ secrets.READ_TOKEN }}
        run: |
          set -euo pipefail
          CLEAN="$(printf '%s' "$READ_PAT" | tr -d '\r\n')"
          BASIC="$(printf 'x-access-token:%s' "$CLEAN" | base64 -w0 2>
