---
# yamllint disable rule:line-length
name: Sync Frontend and Backend Repos

'on':
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: sync-repos
  cancel-in-progress: true

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout analysis repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WRITE_TOKEN || github.token }}
          fetch-depth: 1

      - name: Configure git
        run: |
          git config user.name "sync-bot"
          git config user.email "sync-bot@krishamaze.com"

      - name: Clean work dirs
        run: rm -rf frontend backend temp-frontend temp-backend

      - name: Checkout Frontend (private repo)
        uses: actions/checkout@v4
        with:
          repository: krishamaze/finetune-ERP-frontend
          ref: feature/dashboard-integration
          path: temp-frontend
          token: ${{ secrets.READ_TOKEN }}
          persist-credentials: false

      - name: Checkout Backend (private repo)
        uses: actions/checkout@v4
        with:
          repository: krishamaze/finetune-ERP-backend
          ref: krishna/implement-phase-a1-admin-api-scaffold
          path: temp-backend
          token: ${{ secrets.READ_TOKEN }}
          persist-credentials: false

      - name: Copy files (excluding git history)
        run: |
          mkdir -p frontend backend
          cp -r temp-frontend/* frontend/ 2>/dev/null || true
          cp -r temp-frontend/.[!.]* frontend/ 2>/dev/null || true
          cp -r temp-backend/*  backend/  2>/dev/null || true
          cp -r temp-backend/.[!.]* backend/ 2>/dev/null || true
          rm -rf temp-frontend temp-backend frontend/.git backend/.git

      - name: Remove sensitive files
        run: |
          find frontend backend -name ".env*" -delete 2>/dev/null || true
          find frontend backend -name "node_modules" -type d -exec rm -rf {} + 2>/dev/null || true
          find frontend backend -name ".git" -type d -exec rm -rf {} + 2>/dev/null || true

      - name: Create sync info
        run: |
          {
            echo "# Repo Sync Information"
            echo
            echo "**Last Synced:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            echo
            echo "**Frontend Branch:** feature/dashboard-integration"
            echo "**Backend Branch:** krishna/implement-phase-a1-admin-api-scaffold"
            echo
            echo "**Frontend Repo:** https://github.com/krishamaze/finetune-ERP-frontend"
            echo "**Backend Repo:** https://github.com/krishamaze/finetune-ERP-backend"
          } > SYNC_INFO.md

      - name: Commit and push changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync repos: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
            echo "Changes synced successfully!"
          fi
