name: Sync Frontend and Backend Repos

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: sync-repos
  cancel-in-progress: true

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      # Checkout the analysis repo with RW token
      - name: Checkout analysis repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WRITE_TOKEN }}   # RW access to analysis repo
          fetch-depth: 1

      - name: Configure git
        run: |
          git config user.name "sync-bot"
          git config user.email "sync-bot@krishamaze.com"

      - name: Clean work dirs
        run: rm -rf frontend backend temp-frontend temp-backend

      # Clone frontend using Bearer token header
      - name: Clone Frontend
        run: |
          echo "Cloning Frontend..."
          git -c http.extraHeader="Authorization: Bearer ${{ secrets.READ_TOKEN }}" \
              clone --depth 1 --branch feature/dashboard-integration \
              https://github.com/krishamaze/finetune-ERP-frontend.git temp-frontend
          echo "Frontend clone successful"

      # Clone backend using Bearer token header
      - name: Clone Backend
        run: |
          echo "Cloning Backend..."
          git -c http.extraHeader="Authorization: Bearer ${{ secrets.READ_TOKEN }}" \
              clone --depth 1 --branch krishna/implement-phase-a1-admin-api-scaffold \
              https://github.com/krishamaze/finetune-ERP-backend.git temp-backend
          echo "Backend clone successful"

      - name: Copy files (excluding git history)
        run: |
          mkdir -p frontend backend
          cp -r temp-frontend/* frontend/ 2>/dev/null || true
          cp -r temp-frontend/.[!.]* frontend/ 2>/dev/null || true
          cp -r temp-backend/*  backend/  2>/dev/null || true
          cp -r temp-backend/.[!.]* backend/ 2>/dev/null || true
          rm -rf temp-frontend temp-backend frontend/.git backend/.git

      - name: Rem
