name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install frontend dependencies
        working-directory: finetune-ERP-frontend-New
        run: npm ci
      - name: Vitest
        working-directory: finetune-ERP-frontend-New
        run: npm test
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install backend dependencies
        working-directory: finetune-ERP-backend-New
        run: pip install -r requirements-test.txt
      - name: Pytest
        working-directory: finetune-ERP-backend-New
        run: pytest
