name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: finetune-ERP-frontend-New/pnpm-lock.yaml
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install frontend dependencies
        working-directory: finetune-ERP-frontend-New
        run: pnpm install --frozen-lockfile
      - name: Vitest
        working-directory: finetune-ERP-frontend-New
        run: pnpm test
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install backend dependencies
        run: pip install -e .[backend,dev,test]
      - name: Pytest
        working-directory: finetune-ERP-backend-New
        run: pytest
